on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: floorballregistry.azurecr.io
        username: ${{ secrets.acr_floorballregistry_username }}
        password: ${{ secrets.acr_floorballregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t floorballregistry.azurecr.io/floorballcluster2:${{ github.sha }}
        docker push floorballregistry.azurecr.io/floorballcluster2:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_floorballcluster2_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep floorballbackend | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace floorballbackend`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: floorballbackend
        container-registry-url: floorballregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_floorballregistry_username }}
        container-registry-password: ${{ secrets.acr_floorballregistry_password }}
        secret-name: floorballcludockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: floorballbackend
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          floorballregistry.azurecr.io/floorballcluster2:${{ github.sha }}
        imagepullsecrets: |
          floorballcludockerauth